name: DevSecOps Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-scan-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Debug files
        run: ls -R

      - name: Build Image
        run: docker build -t ghcr.io/omgmmui/node-app:latest ./04-Container-Security

      - name: Install Trivy
        run: |
          sudo apt-get update
          sudo apt-get install -y wget
          wget https://github.com/aquasecurity/trivy/releases/latest/download/trivy_0.50.1_Linux-64bit.deb
          sudo dpkg -i trivy_0.50.1_Linux-64bit.deb

      - name: Scan Image
        run: trivy image ghcr.io/omgmmui/node-app:latest

      - name: Push Image
        run: docker push ghcr.io/omgmmui/node-app:latest
